#-------------------------------
# General Site Settings
title: Curiodo
logo: logo.svg
description: Nothing special at all :D


#-------------------------------
# Author Settings
author:
  name: Do Do
  image: avt.png
  say-hello: <strong>Curiodo</strong> - Curious Đô Đô reveals wonders through simple tales.
  say-hello-vi: <strong>Curiodo</strong> - Đô Đô với những câu chuyện giản đơn.

#-------------------------------
# Contact links
facebook: https://www.facebook.com/supremedodo.5/
instagram: https://www.instagram.com/do.do.5/


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: louis # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: do.do.5


#-------------------------------
# Google Analytics
google-analytics: G-43F2E9L06V # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
